export const lollipops = [
  {
    flavourTop: "#C35671",
    flavourMiddle: "#E93A3A",
    flavourBottom: "#D52020",
    name: "Crimson Blaze",
  },
  {
    flavourTop: "#FF6B81",
    flavourMiddle: "#FF3E6B",
    flavourBottom: "#FF1F58",
    name: "Strawberry Passion",
  },
  {
    flavourTop: "#FFD53E",
    flavourMiddle: "#FFAA00",
    flavourBottom: "#FF8000",
    name: "Tropical Sunset",
  },
  {
    flavourTop: "#6688FF",
    flavourMiddle: "#3366FF",
    flavourBottom: "#0033CC",
    name: "Blueberry Burst",
  },
  {
    flavourTop: "#50D2C2",
    flavourMiddle: "#00BFA6",
    flavourBottom: "#009688",
    name: "Minty Fresh",
  },
  // Adding more lollipops
  {
    flavourTop: "#FFC0CB",
    flavourMiddle: "#FF69B4",
    flavourBottom: "#FF1493",
    name: "Cotton Candy Delight",
  },
  {
    flavourTop: "#FF6347",
    flavourMiddle: "#FF4500",
    flavourBottom: "#FF8C00",
    name: "Tangy Tangerine",
  },
  {
    flavourTop: "#7FFF00",
    flavourMiddle: "#32CD32",
    flavourBottom: "#228B22",
    name: "Zesty Lime",
  },
  {
    flavourTop: "#FF1493",
    flavourMiddle: "#FF00FF",
    flavourBottom: "#8A2BE2",
    name: "Grape Fizz",
  },
  {
    flavourTop: "#4169E1",
    flavourMiddle: "#0000FF",
    flavourBottom: "#00008B",
    name: "Electric Blue",
  },
  {
    flavourTop: "#F08080",
    flavourMiddle: "#CD5C5C",
    flavourBottom: "#B22222",
    name: "Cherry Blast",
  },
  {
    flavourTop: "#FFFF00",
    flavourMiddle: "#FFD700",
    flavourBottom: "#FFA500",
    name: "Sunny Citrus",
  },
  {
    flavourTop: "#4682B4",
    flavourMiddle: "#00CED1",
    flavourBottom: "#20B2AA",
    name: "Ocean Breeze",
  },
  {
    flavourTop: "#800080",
    flavourMiddle: "#4B0082",
    flavourBottom: "#483D8B",
    name: "Purple Haze",
  },
  {
    flavourTop: "#7CFC00",
    flavourMiddle: "#ADFF2F",
    flavourBottom: "#32CD32",
    name: "Green Apple Crunch",
  },
  {
    flavourTop: "#FFE4E1",
    flavourMiddle: "#FFB6C1",
    flavourBottom: "#FF69B4",
    name: "Bubblegum Dream",
  },
  {
    flavourTop: "#FFDEAD",
    flavourMiddle: "#F4A460",
    flavourBottom: "#D2691E",
    name: "Toffee Temptation",
  },
  {
    flavourTop: "#00FFFF",
    flavourMiddle: "#00CED1",
    flavourBottom: "#008B8B",
    name: "Turquoise Treat",
  },
  {
    flavourTop: "#FA8072",
    flavourMiddle: "#FFA07A",
    flavourBottom: "#E9967A",
    name: "Coral Crush",
  },
  {
    flavourTop: "#87CEEB",
    flavourMiddle: "#4682B4",
    flavourBottom: "#4169E1",
    name: "Sky High",
  },
  {
    flavourTop: "#FFA07A",
    flavourMiddle: "#FF7F50",
    flavourBottom: "#FF6347",
    name: "Sizzling Salmon",
  },
  {
    flavourTop: "#2E8B57",
    flavourMiddle: "#3CB371",
    flavourBottom: "#8FBC8F",
    name: "Minty Forest",
  },
  {
    flavourTop: "#DDA0DD",
    flavourMiddle: "#BA55D3",
    flavourBottom: "#9932CC",
    name: "Berry Blast",
  },
  {
    flavourTop: "#FFFF66",
    flavourMiddle: "#FFD700",
    flavourBottom: "#FFC0CB",
    name: "Lemon Lush",
  },
  {
    flavourTop: "#800000",
    flavourMiddle: "#8B0000",
    flavourBottom: "#B22222",
    name: "Fiery Inferno",
  },
  {
    flavourTop: "#20B2AA",
    flavourMiddle: "#008080",
    flavourBottom: "#2F4F4F",
    name: "Teal Temptation",
  },
  {
    flavourTop: "#FF4500",
    flavourMiddle: "#FF6347",
    flavourBottom: "#FF7F50",
    name: "Tangy Tango",
  },
  {
    flavourTop: "#48D1CC",
    flavourMiddle: "#00CED1",
    flavourBottom: "#008B8B",
    name: "Aqua Fusion",
  },
  {
    flavourTop: "#DEB887",
    flavourMiddle: "#D2B48C",
    flavourBottom: "#BC8F8F",
    name: "Caramel Delight",
  },
  {
    flavourTop: "#F0E68C",
    flavourMiddle: "#FFD700",
    flavourBottom: "#FFA500",
    name: "Golden Glow",
  },
  {
    flavourTop: "#87CEEB",
    flavourMiddle: "#4682B4",
    flavourBottom: "#4169E1",
    name: "Icy Waters",
  },
  {
    flavourTop: "#9400D3",
    flavourMiddle: "#8A2BE2",
    flavourBottom: "#4B0082",
    name: "Purple Passion",
  },
  {
    flavourTop: "#00FF00",
    flavourMiddle: "#32CD32",
    flavourBottom: "#008000",
    name: "Vivid Verde",
  },
  {
    flavourTop: "#FFB6C1",
    flavourMiddle: "#FF69B4",
    flavourBottom: "#FF1493",
    name: "Pink Pizzazz",
  },
  {
    flavourTop: "#FFFF00",
    flavourMiddle: "#FFD700",
    flavourBottom: "#FFA500",
    name: "Yellow Sunshine",
  },
];
